json.id @user.id
json.username @user.username
json.bio @user.bio
json.latitude @user.latitude
json.longitude @user.longitude
json.picture_url @user.picture.url
json.age @user.age
json.gender @user.gender
json.matches1 @user.matches1
json.matches2 @user.matches2
